version: "3"

services:
  gateway:
    image: traefik:2.7
    logging:
      options:
        max-file: "5"
        max-size: "100m"
        compress: "true"
    container_name: docker-vpn-gateway
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      svc-vpn-gateway:
    ports:
      - ${GATEWAY_HTTP_BIND:-80}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --log.level=error
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.defaultRule=Host(`{{ index .Labels "expose.vhost"}}`)
      - --providers.docker.constraints=Label(`expose.service`,`vpn`)
      - --entrypoints.http.address=:80

  # Catch-all default vhost
  default:
    image: nginx:stable-alpine
    logging:
      options:
        max-file: "5"
        max-size: "100m"
        compress: "true"
    container_name: docker-vpn-default
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      svc-vpn-network:
        priority: 500
      svc-vpn-gateway:
        priority: 100
    labels:
      - expose.service=vpn
      - traefik.http.routers.default.rule=HostRegexp(`{default:.*}`) 
      - traefik.enable=true
      - traefik.docker.network=svc-vpn-gateway
      - traefik.http.routers.default.entrypoints=http
      - traefik.http.middlewares.server-header.headers.customresponseheaders.server=service-vpn-gateway
      - traefik.http.routers.default.priority=1
      - traefik.http.routers.default.middlewares=server-header
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  svc-vpn-gateway:
    name: svc-vpn-gateway
    driver_opts:
      com.docker.network.bridge.name: br-vpn-gateway

  svc-vpn-network:
    name: svc-vpn-network
    driver_opts:
      com.docker.network.bridge.name: br-vpn-network
