#!/usr/bin/env bash
if docker compose version &>/dev/null
then
  exec docker compose -f docker-compose-public.yml up --quiet-pull --force-recreate -d
fi
if docker-compose version &>/dev/null
then
  exec docker-compose -f docker-compose-public.yml up --quiet-pull --force-recreate -d
fi
echo "missing docker-compose or \"docker compose\"..."
exit 1
