#!/usr/bin/env bash
if docker compose version &>/dev/null
then
  exec docker compose down
if docker-compose version &>/dev/null
then
  exec docker-compose down
fi
echo "missing docker-compose or \"docker compose\"..."
exit 1
