version: "3"

services:
  gateway:
    image: traefik:2.7
    logging:
      options:
        max-file: "5"
        max-size: "100m"
        compress: "true"
    container_name: docker-public-gateway
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      svc-wan-gateway:
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/acme
    command:
      - --log.level=error
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.defaultRule=Host(`{{ index .Labels "expose.vhost"}}`)
      - --providers.docker.constraints=Label(`expose.service`,`wan`)
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http

  # Catch-all default vhost
  default:
    image: nginx:stable-alpine
    logging:
      options:
        max-file: "5"
        max-size: "100m"
        compress: "true"
    container_name: docker-public-gateway-default
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      svc-wan-network:
        priority: 500
      svc-wan-gateway:
        priority: 100
    labels:
      - expose.service=wan
      - traefik.http.routers.default.rule=HostRegexp(`{default:.*}`) 
      - traefik.enable=true
      - traefik.docker.network=svc-wan-gateway
      - traefik.http.routers.default.entrypoints=http
      - traefik.http.middlewares.server-header.headers.customresponseheaders.server=service-wan-gateway
      - traefik.http.routers.default.priority=1
      - traefik.http.routers.default.middlewares=server-header
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  svc-wan-gateway:
    name: svc-wan-gateway
    driver_opts:
      com.docker.network.bridge.name: br-wan-gateway

  svc-wan-network:
    name: svc-wan-network
    driver_opts:
      com.docker.network.bridge.name: br-wan-network

volumes:
  acme:
    name: service-wan-gateway-acme
