version: "3"

services:
 hello4nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    labels:
      - expose.vhost=hello.example.com
      - traefik.enable=true
      - traefik.docker.network=service-gateway
      - traefik.http.routers.hello.entrypoints=http
      - traefik.http.routers.hellos.entrypoints=https
      - traefik.http.routers.hellos.tls=true
      - traefik.http.routers.hellos.tls.certresolver=letsencrypt
      - traefik.http.middlewares.redirect2https.redirectscheme.scheme=https
      - traefik.http.middlewares.server-header.headers.customresponseheaders.server=service-gateway
      - traefik.http.routers.hello.middlewares=server-header,redirect2https
      - traefik.http.routers.hellos.middlewares=server-header
    networks:
      - default
      - service-gateway

networks:
  service-gateway:
    external: true
