version: "3"
name: "ingress"

services:
  ingress:
    image: "traefik:${TRAEFIK_VERSION}"
      #init: true
    logging:
      options:
        max-file: "10"
        max-size: "25m"
        compress: "true"
    container_name: "${COMPOSE_PROJECT_NAME}-traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - ingress
    ports:
      - ${INGRESS_HTTP_BIND:-80}:80
      - ${INGRESS_HTTPS_BIND:-443}:443
    environment:
      DASHBOARD:        "${DASHBOARD:-}"
      DASHBOARD_USERS:  "${DASHBOARD_USERS:-default}"
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - acme:/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --log.level=error
      - --accesslog=true
      - --providers.file.filename=/config/config.yaml
      - --providers.file.watch=false
      - --providers.docker.network=ingress
      - --providers.docker.defaultRule=Host(`{{ index .Labels "expose.vhost"}}`)
      - --providers.docker.constraints=LabelRegex(`expose.ingress`,`(?i)^(yes|true|on|enable|allow|activate|active|use)$`) || LabelRegex(`expose.vhost`,`.+`)
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.certresolver=http
      - --api.dashboard=true
      - --api.disabledashboardad=true
      - --certificatesresolvers.http.acme.storage=/acme/http-acme.json
      - --certificatesresolvers.http.acme.httpchallenge.entrypoint=http
      - --global.checknewversion=false
      - --global.sendanonymoususage=false

  default:
    image: wyga/http:204
    container_name: "${COMPOSE_PROJECT_NAME}-default"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-file: "10"
        max-size: "25m"
        compress: "true"
    networks:
      - ingress
    labels:
      - expose.ingress=yes
      - traefik.http.routers.ingress-default.rule=HostRegexp(`{default:.*}`)
      - traefik.http.routers.ingress-default.entrypoints=http
      - traefik.http.routers.ingress-default.priority=1

networks:
  ingress:
    name: "ingress"
    external: true

volumes:
  acme:
    name: "ingress-acme"
    external: true
